version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
volumes:
  data_value: